### ISSUE TITLE
An error with the __init__() of gamba model

### ISSUE THREAD

**Issue by zjxx** [SkyworkAI/Gamba#6]
Thank you for your great work.
As I was running the test.sh,I seemed to encounter a problem with the gamba_model.py

`Traceback (most recent call last):
  File "gamba_infer.py", line 22, in <module>
    from core.gamba_models import Gamba
  File "/root/autodl-tmp/Gamba/core/gamba_models.py", line 349, in <module>
    class Gamba(torch.nn.Module):
  File "/root/autodl-tmp/Gamba/core/gamba_models.py", line 442, in Gamba
    def forward_gaussians(self, data):
TypeError: __init__() takes 1 positional argument but 2 were given`

**Comment by luminous-Nc** [comment]
I have a similar issue when I was running test.sh: `python gamba_infer.py --model-type gamba --resume ./checkpoint/gamba_ep399.pth --workspace workspace_test --test_path ./data_test`

```
 File "D:\Gamba\gamba_infer.py", line 20, in <module>
    from core.options import AllConfigs, Options
 File "D:\Gamba\core\options.py", line 110, in <module>
    AllConfigs = tyro.extras.subcommand_type_from_defaults(config_defaults, config_doc)
File "D:\Gamba\venv\lib\site-packages\tyro\extras\_base_configs.py", line 132, in subcommand_type_from_defaults
    assert len(defaults) >= 2, "At least two subcommands are required."
AssertionError: At least two subcommands are required.
```

**Comment by florinshen** [comment]
seems bugs raised from tyro version, can you pls show me your tyro version info by running this command 
`pip show tyro`
and here is my tyro info, 
```
Name: tyro
Version: 0.8.5
Summary: Strongly typed, zero-effort CLI interfaces
Home-page: 
Author: 
Author-email: brentyi <brentyi@berkeley.edu>
License: MIT
Location: /opt/conda/lib/python3.10/site-packages
Requires: docstring-parser, rich, shtab, typing-extensions
Required-by: #N/A
```

**Comment by zjxx** [comment]
> seems bugs raised from tyro version, can you pls show me your tyro version info by running this command `pip show tyro` and here is my tyro info,
> 
> ```
> Name: tyro
> Version: 0.8.5
> Summary: Strongly typed, zero-effort CLI interfaces
> Home-page: 
> Author: 
> Author-email: brentyi <brentyi@berkeley.edu>
> License: MIT
> Location: /opt/conda/lib/python3.10/site-packages
> Requires: docstring-parser, rich, shtab, typing-extensions
> Required-by: #N/A
> ```

As I change the tyro version from 0.8.10 to .8.5,the problem remains.  I follow the solution from [DJNing](https://github.com/SkyworkAI/Gamba/issues/1) and get the error `Traceback (most recent call last): File "gamba_infer.py", line 22, in <module> from core.gamba_models import Gamba File "/root/autodl-tmp/Gamba/core/gamba_models.py", line 349, in <module> class Gamba(torch.nn.Module): File "/root/autodl-tmp/Gamba/core/gamba_models.py", line 442, in Gamba def forward_gaussians(self, data): TypeError: __init__() takes 1 positional argument but 2 were given`
Otherwise I get the error same as luminous-Nc

**Comment by luminous-Nc** [comment]
Here is my tyro info
```
(venv) PS D:\Gamba> pip show tyro
Name: tyro
Version: 0.8.10                                                                         
Summary: Strongly typed, zero-effort CLI interfaces                                     
Home-page:                                                                              
Author:                                                                                 
Author-email: brentyi <brentyi@berkeley.edu>                                            
License: MIT                                                                            
Location: d:\gamba\venv\lib\site-packages                                  
Requires: colorama, docstring-parser, eval-type-backport, rich, shtab, typing-extensions
Required-by: 

```

**Comment by HIT-CS-Kn1ght** [comment]
> Thank you for your great work. As I was running the test.sh,I seemed to encounter a problem with the gamba_model.py
> 
> `Traceback (most recent call last): File "gamba_infer.py", line 22, in <module> from core.gamba_models import Gamba File "/root/autodl-tmp/Gamba/core/gamba_models.py", line 349, in <module> class Gamba(torch.nn.Module): File "/root/autodl-tmp/Gamba/core/gamba_models.py", line 442, in Gamba def forward_gaussians(self, data): TypeError: __init__() takes 1 positional argument but 2 were given`

change the line 441 in Gamba/core/gamba_models.py to `@torch.no_grad()`
